### PR TITLE
no-display-none

### PR DESCRIPTION
**Pull request by YozhikM**
/cc @evilebottnawi 
#1

### CODE REVIEW

**Comment by YozhikM** [comment]
@evilebottnawi 
I'm still not sure about that rule. on the one hand, it will help accessibility, and on the other-there will be many unexpected for user errors

**Comment by evilebottnawi** [comment]
@YozhikM it is normal rule, people should use `warning` for this rule for better review code, you can add this readme

**Comment by evilebottnawi** [comment]
@YozhikM also we should put this rule in wild to get feedback and improve this in future

**Comment by evilebottnawi** [comment]
@YozhikM i think many people use `display: none` for internal purposes, better use `warning` for this rule not error https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#severities-error--warning, some rules in `eslint` also recommend use `warning` instead of `error`

**Pull request merged**
