### PR TITLE
line-height-is-vertical-rhythmed

### PR DESCRIPTION
**Pull request by igorkamyshev**
I will be grateful for any feedback.

### CODE REVIEW

**Comment by igorkamyshev** [comment]
@YozhikM hey! Thanks for feedback.

I'll fix it.

**Comment by igorkamyshev** [comment]
What about `text-lines-is-distinguishable`?

**Comment by YozhikM** [comment]
or `line-height-is-vertical-rhythmed`
/cc @evilebottnawi

**Comment by igorkamyshev** [comment]
@YozhikM wow, great! Thanks.

**Comment by igorkamyshev** [comment]
Done.

**Pull request merged**
