### PR TITLE
Add recommended shareable config

### PR DESCRIPTION
**Pull request by silvenon**

### CODE REVIEW

**Comment by ntwb** [comment]
Only 4 of the rules are _recomended_: https://github.com/YozhikM/stylelint-a11y#rules

**Comment by silvenon** [comment]
Oops, I just blindly copied the "recommended config". I'll update the PR accordingly.

**Comment by silvenon** [comment]
Done. I updated that part of the documentation to reflect the shareable config, I hope that's ok.

**Comment by YozhikM** [comment]
LGTM.

**Pull request merged**
