### PR TITLE
no-spread-text

### PR DESCRIPTION
**Pull request by igorkamyshev**
Hello! 🖖

I create new rule `no-spread-text`.

Please, review PR and give me your feedback.

### CODE REVIEW

**Comment by YozhikM** [comment]
@igorkamyshev Fine, but look: with this rule there are several problems.
1. It should only apply to `<p>`.
2. In most cases, selector `p` is not used, but classes.
Therefore, we need to find a way to determine that the class is applied to the text section. For example, by the fact that the selector has styles for the font or the size of the text.

However, this can work for Hedging. Therefore, my proposal is an intermediate solution. Any thoughts?

**Comment by igorkamyshev** [comment]
@YozhikM okey 👍. I will add checking for this cases.

**Comment by igorkamyshev** [comment]
@YozhikM hello! I added some heuristics for defining node appointment. Also, add a warning message to readme. What do you think, such rule may useful for community?

**Comment by YozhikM** [comment]
@igorkamyshev Sure, I think we can try

**Comment by YozhikM** [comment]
Released in 1.1.6. Thx!

**Pull request merged**
